# -*- coding: utf-8 -*-
"""Pizza Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT1TS6i2Ady2Hbs2OnfVo4XnYh2Ux7bF

**Pizza Sales Analysis**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px

"""**Import Data Libraries**"""

df = pd.read_csv("/content/pizza_sales.csv")

"""**Raw Data**


"""

df.head()

print("The Metadata Of The Dataset :  ", df.shape)

"""**KPI**"""

total_revenue = df["total_price"].sum()
total_pizza_sold = df["quantity"].sum()
total_orders = df["order_id"].nunique()
avg_order_value = total_revenue / total_orders
avg_pizza_per_order = total_pizza_sold / total_orders

print(f"Total Revenue: ${total_revenue:.2f}")
print(f"Total Pizza Sold: {total_pizza_sold}")
print(f"Total Orders: {total_orders}")
print(f"Average Order Value: ${avg_order_value:.2f}")
print(f"Average Pizzas Per Order: {avg_pizza_per_order:.2f}")

"""**Chart**

**Ingredient Analysis**
"""

ingredient = (
              df['pizza_ingredients']
              .str.split(",")
              .explode()
              .value_counts()
              .reset_index()
              .rename(columns={'index': 'Count', 'pizza_ingredients': 'Ingredients'})
    )
print(ingredient.head(10))

"""**Daily Trend - Total Orders**"""

df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

df['day_name'] = df['order_date'].dt.day_name()

weekday_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

df['day_name'] = pd.Categorical(df['day_name'], categories=weekday_order, ordered=True)

ordered_by_day = df.groupby('day_name', observed=False)['order_id'].count()

ax = ordered_by_day.plot(kind='bar', figsize=(8,5), color='skyblue', edgecolor='black')

plt.title('Total Orders by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Orders')
plt.xticks(rotation=45)

for i, val in enumerate(ordered_by_day):
    plt.text(i, val + 50, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Daily Trend - Total Revenue**"""

df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

df['day_name'] = df['order_date'].dt.day_name()

weekday_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

df['day_name'] = pd.Categorical(df['day_name'], categories=weekday_order, ordered=True)

ordered_by_day = df.groupby('day_name', observed=False)['total_price'].sum()

ax = ordered_by_day.plot(kind='bar', figsize=(8,5), color='orange', edgecolor='black')

plt.title('Total Revenue by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)

for i, val in enumerate(ordered_by_day):
    plt.text(i, val + 50, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Hourly Trend - Total Order**"""

df['order_time'] = pd.to_datetime(df['order_time'], errors='coerce')
df = df.dropna(subset=['order_time'])

df['order_hour'] = df['order_time'].dt.hour
orders_by_hour = df.groupby('order_hour')['order_id'].count()

plt.figure(figsize=(10,5))
ax = orders_by_hour.plot(kind='bar', color='maroon', edgecolor='black')

plt.title("Total Orders by Hour of Day")
plt.xlabel("Hour of Day (24-Hour Format)")
plt.ylabel("Number of Orders")
plt.xticks(rotation=0)

for i, val in enumerate(orders_by_hour):
    plt.text(i, val + 5, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Monthly Trend - Total Orders**"""

df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

df['month_name'] = df['order_date'].dt.month_name()

month_order = ['January','February','March','April','May','June','July','August','September','October','November','December']

df['month_name'] = pd.Categorical(df['month_name'], categories=month_order, ordered=True)

ordered_by_month = df.groupby('month_name', observed=False)['order_id'].count()

plt.figure(figsize=(10,5))
plt.fill_between(ordered_by_month.index,ordered_by_month.values, color='green', alpha=0.6)
plt.plot(ordered_by_month.index, ordered_by_month.values, color='black', marker='o')

plt.title('Total Orders by Month')
plt.xlabel('Month')
plt.ylabel('Number of Orders')
plt.xticks(rotation=45)

for i, val in enumerate(ordered_by_month):
  plt.text(i, val + 20, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**`% Of Sales By Category`**"""

category_sales = df.groupby('pizza_category')['total_price'].sum()
category_pct = category_sales/category_sales.sum() * 100

plt.figure(figsize=(7,7))
colors = plt.get_cmap('tab20').colors

plt.pie(
    category_pct,
    labels=category_pct.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=colors,
    wedgeprops={'edgecolor':'black', 'width':0.4}
)

plt.title('Percentage of Sales by Category')
plt.show()

"""**`% Sales By Pizza Size & Category`**"""

sales_pivot = df.pivot_table(
    index='pizza_category',
    columns='pizza_size',
    values='total_price',
    aggfunc='sum',
    fill_value=0
)

sales_pivot_pct = sales_pivot / sales_pivot.sum().sum() * 100

plt.figure(figsize=(10,6))
sns.heatmap(sales_pivot_pct, annot=True, fmt='.1f', cmap='YlGnBu', linewidths=0.5)
plt.title('Percentage of Sales by Pizza Size and Category')
plt.ylabel('Pizza Category')
plt.xlabel('Pizza Size')
plt.show()

"""**Total Pizza Sold By Pizza Category**"""

pizza_by_category = df.groupby('pizza_category')['quantity'].sum()

colors = list(plt.get_cmap('tab20').colors)

colors = colors[:len(pizza_by_category)]

ax = pizza_by_category.plot(
    kind='bar', figsize=(8,5), color=colors, edgecolor='black'
)

plt.title('Total Pizza Sold by Pizza Category')
plt.xlabel('Pizza Category')
plt.ylabel('Total Quantity Sold')
plt.xticks(rotation=45)

for i, val in enumerate(pizza_by_category):
    plt.text(i, val + 5, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Top 5 Best Selling Pizzas - Total Orders**


"""

pizza_by_name = df.groupby('pizza_name')['quantity'].sum()

top5 = pizza_by_name.sort_values(ascending=False).head(5)

ax = top5.plot(kind='bar', figsize=(8,5), color='red', edgecolor='black')

plt.title('Top 5 Best Selling Pizzas by Total Orders')
plt.xlabel('Pizza Name')
plt.ylabel('Total Pizza Sold')
plt.xticks(rotation=45)

for i, val in enumerate(top5):
    plt.text(i, val + 2, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Top 5 Best Selling Pizzas - Total Sales

"""

pizza_by_name = df.groupby('pizza_name')['total_price'].sum()

top5 = pizza_by_name.sort_values(ascending=False).head(5)

ax = top5.plot(kind='bar', figsize=(8,5), color='grey', edgecolor='black')

plt.title('Top 5 Pizzas by Revenue')
plt.xlabel('Pizza Name')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)

for i, val in enumerate(top5):
    plt.text(i, val + 2, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

"""**Bottom 5 Best Selling Pizzas - Total Sales**

"""

pizza_by_name = df.groupby('pizza_name')['total_price'].sum()

bottom5 = pizza_by_name.sort_values(ascending=True).head(5)

ax = bottom5.plot(kind='bar', figsize=(8,5), color='purple', edgecolor='black')

plt.title('bottom 5 Pizzas by Revenue')
plt.xlabel('Pizza Name')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)

for i, val in enumerate(bottom5):
    plt.text(i, val + 2, str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

